<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TerakarsaApp.PrintService-2bdf5f45-2e45-4bcf-808f-7d969f680f60</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerakarsaApp.Shared\TerakarsaApp.Shared.csproj" />
  </ItemGroup>
</Project>
